const STANDARD_CHANGES=[{kind:'당기 시행',standard:'K-IFRS 2021-2023 연차개선',summary:'현금흐름표·최초채택·금융상품 등 관련 기준 개정',announced:'2024-11-22',effective:'2026-01-01',status:'적용 확인 필요',url:'https://www.kasb.or.kr/front/board/List2006.do'},{kind:'당기 시행',standard:'금융상품의 분류와 측정 개정',summary:'금융상품 분류·측정 및 공시 관련 개정',announced:'2024-11-22',effective:'2026-01-01',status:'적용 확인 필요',url:'https://www.kasb.or.kr/front/board/List2006.do'},{kind:'당기 시행',standard:'교환가능성 결여',summary:'외화 환산 시 교환가능성 판단 관련 개정',announced:'2023-12-22',effective:'2026-01-01',status:'관련성 검토',url:'https://www.kasb.or.kr/front/board/List2006.do'},{kind:'향후 시행',standard:'K-IFRS 제1118호 재무제표 표시와 공시',summary:'재무제표 표시 및 공시 체계 변경',announced:'2025-11-21',effective:'2027-01-01',status:'사전 검토',url:'https://www.kasb.or.kr/front/board/List2006.do'}];
STANDARD_CHANGES.forEach(r=>{r.basis='K-IFRS|공기업·준정부기관 회계기준'});
function standardKindForYear(row,year){return year==='2027'&&row.effective.startsWith('2027')?'당기 시행':year==='2026'&&row.effective.startsWith('2027')?'향후 시행':row.kind}
function resetStandardStats(){document.getElementById('stdEffective').textContent='—';document.getElementById('stdFuture').textContent='—';document.getElementById('stdNeed').textContent='—';document.getElementById('standardsBody').innerHTML='<tr><td colspan="7" class="empty-row">결산연도와 적용기준을 선택한 후 변경사항 조회를 눌러 주세요.</td></tr>'}
function updateStandardStats(rows,year){const effective=rows.filter(r=>standardKindForYear(r,year)==='당기 시행').length;const future=rows.filter(r=>standardKindForYear(r,year)==='향후 시행').length;const need=rows.filter(r=>r.status.includes('확인')||r.status==='관련성 검토').length;document.getElementById('stdEffective').textContent=effective;document.getElementById('stdFuture').textContent=future;document.getElementById('stdNeed').textContent=need}
function applyView(view){const dashboard=document.getElementById('dashboard');const standards=document.getElementById('standardsPanel');if(view==='standards'){dashboard.style.display='none';standards.classList.add('visible');resetStandardStats()}else{standards.classList.remove('visible');dashboard.style.display='block'}}
function openStandards(fromHistory=false){if(!fromHistory&&history.state?.arcView!=='standards'){history.pushState({arcView:'standards'},'',`${location.pathname}${location.search}#standards`)}applyView('standards')}
function closeStandards(){applyView('dashboard');if(history.state?.arcView==='standards'){history.replaceState({arcView:'dashboard'},'',`${location.pathname}${location.search}`)}}
window.addEventListener('popstate',event=>applyView(event.state?.arcView==='standards'?'standards':'dashboard'))
function openSource(event,url){event.preventDefault();event.stopPropagation();const returnUrl=`${location.pathname}${location.search}#standards`;const sourceWindow=window.open(url,'_blank','noopener,noreferrer');if(sourceWindow){try{sourceWindow.opener=null;sourceWindow.focus()}catch(_){ }return false}history.pushState({arcView:'standards',arcReturn:true},'',returnUrl);window.location.assign(url);return false}
function renderStandards(rows){const selectedBasis=document.getElementById('standardsBasis')?.value;const selectedYear=document.getElementById('standardsYear')?.value;updateStandardStats(rows,selectedYear);const body=rows.length?rows.map(r=>`<tr><td><span class="badge ${standardKindForYear(r,selectedYear)==='당기 시행'?'cost':'asset'}">${standardKindForYear(r,selectedYear)}</span></td><td>${esc(r.standard)}</td><td>${esc(r.summary)}</td><td>${r.announced}</td><td>${r.effective}</td><td>${esc(selectedBasis==='공기업·준정부기관 회계기준'?'기관 적용 여부 확인':r.status)}</td><td><button type="button" class="source-link" data-source-url="${esc(r.url)}" onclick="return openSource(event,this.dataset.sourceUrl)">원문 확인 ↗</button></td></tr>`).join(''):`<tr><td colspan="7" class="empty-row">선택한 적용기준에 연결된 변경자료가 없습니다. 공식 원문과 기관 적용기준을 확인해 주세요.</td></tr>`;document.getElementById('standardsBody').innerHTML=body}
function filterStandards(){const year=document.getElementById('standardsYear').value;const yearMatches=r=>year==='2026'||r.effective.startsWith(year);renderStandards(STANDARD_CHANGES.filter(r=>yearMatches(r)));}
const ASSET_WORDS=['공사','건물','구축물','기계장치','장비','자산취득','시설','취득','소프트웨어','설계','토지'];
const EXCLUDE_WORDS=['제거','정산완료','이미 대체','환원완료'];
const REVIEW_HEADERS=['계정과목','승인일자','거래처명','결의상세','차변','대변','사업ID','비목ID','비목명','세부항목코드','세부항목명','결의부서명','결의자명','결의번호','검토결과','계정과목코드','계정과목명'];
const JOURNAL_HEADERS=['상태','계정과목명','계정과목코드','차대구분','차변금액','대변금액','사업ID','세부내역','거래처명','actsYy','bzplCd','rsolNo','bdgtBzplCd','aplDeptCd','dtalAtclCd','actrCd','actrNm','drcrDivCd2','pendMngeDivCd','pendNo','acotClssCd','evidNo','evidMngeNo','acotTyCd','mngeAtclCd1','ramtMngeYn1','mngeAtclVal1','mngeAtclValNm1','mngeAtclCd2','ramtMngeYn2','mngeAtclVal2','mngeAtclValNm2','mngeAtclCd3','ramtMngeYn3','mngeAtclVal3','mngeAtclValNm3','imgnAccnInstCd','bankCd','imgnAccnNo','imgnAccnDlngDt','imgnAccnDlngPtm','imgnAccnDlngSrno','fincAstsNo','dlngItmnSrno','계좌번호','금융자산명'];
const rowGroupKey=row=>{const vendor=pick(row,['거래처명','거래처','vendor']);const detail=pick(row,['결의상세','세부내역','세부항목명']);const project=pick(row,['사업ID','사업ID명','사업']);if(!vendor&&!detail&&!project)return '';return [vendor,detail,project].join('|')};
function pairedStates(rows){const groups=new Map();rows.forEach((row,index)=>{const key=rowGroupKey(row);if(!key)return;const g=groups.get(key)||{debit:0,credit:0,indexes:[]};g.debit+=money(pick(row,['차변','차변금액']));g.credit+=money(pick(row,['대변','대변금액']));g.indexes.push(index);groups.set(key,g)});const states=new Map();for(const g of groups.values()){if(g.debit>0&&g.credit>0){const matched=Math.abs(g.debit-g.credit)<0.5;g.indexes.forEach(i=>states.set(i,matched?'exclude':'confusion'))}}return states};
const pick=(row,names)=>{for(const n of names){if(Object.prototype.hasOwnProperty.call(row,n)&&String(row[n]).trim()!=='')return String(row[n]).trim();}const key=Object.keys(row).find(k=>names.some(n=>k.includes(n)));return key?String(row[key]??'').trim():''};
const money=v=>{const n=Number(String(v).replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0};
const originalAmount=row=>{const debit=money(pick(row,['차변','차변금액']));const credit=money(pick(row,['대변','대변금액']));const amount=money(pick(row,['금액','금액(원)']));return debit||credit||amount};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function findMappedAccount(row){const code=pick(row,['비목코드','비목ID','비목 코드','bdgtCd']);const detailCode=pick(row,['세부항목코드','세부항목 코드','dtalAtclCd']);const budget=pick(row,['비목명','비목','budgetName']);const detail=pick(row,['세부항목명','세부항목','세부내역']);const match=(window.MAPPING_TABLE||[]).find(m=>(code&&String(m['비목코드']).trim()===code)&&(detailCode&&String(m['세부항목']).trim()===detailCode))||(window.MAPPING_TABLE||[]).find(m=>String(m['비목명']??'').trim()===budget&&String(m['세부항목명']??'').trim()===detail);return match&&String(match['계정과목']??'').trim()?{accountCode:String(match['계정과목']).trim(),accountName:String(match['계정과목명']??'').trim()}:null}
function classify(row,pairState){
 const text=Object.values(row).join(' ');
 const no=pick(row,['결의번호','결의번호명','rsolNo','전표번호']);
 const vendor=pick(row,['거래처명','거래처','vendor']);
 const amount=pick(row,['금액','차변','대변','차변금액','대변금액','금액(원)']);
 const budget=pick(row,['비목명','비목','budgetName']);
 const detail=pick(row,['세부항목명','세부항목','세부내역']);
 if(pairState==='exclude') return {type:'exclude',label:'대상제외',reason:'거래처·결의상세 기준 차변·대변 선급금 금액이 상계되어 잔액 0'};
 if(pairState==='confusion') return {type:'confusion',label:'분류혼선',reason:'차변·대변 선급금 행은 연결되지만 금액이 일치하지 않아 잔액 확인 필요'};
 if(EXCLUDE_WORDS.some(w=>text.includes(w))) return {type:'exclude',label:'대상제외',reason:'원장 내용상 이미 제거·정산된 항목'};
 if(ASSET_WORDS.some(w=>text.includes(w))) return {type:'asset',label:'자산',reason:'공사·자산 관련 키워드 포함'};
 const match=findMappedAccount(row);
 if(match) return {type:'cost',label:'비용',reason:`매핑표 일치 · ${match.accountCode} ${match.accountName}`,...match};
 return {type:'confusion',label:'분류혼선',reason:'비목·세부항목 매핑 또는 차변·대변 연결 근거 확인 필요'};
}
function renderResults(rows,fileName){
  const pairStates=pairedStates(rows);
  const results=rows.map((r,i)=>({row:r,result:classify(r,pairStates.get(i))}));
  latestResults=results;
  const counts={cost:0,asset:0,confusion:0,exclude:0};results.forEach(x=>counts[x.result.type]++);
  document.getElementById('countAll').textContent=results.length;
  document.getElementById('countCost').textContent=counts.cost;
  document.getElementById('countAsset').textContent=counts.asset;
  document.getElementById('countHold').textContent=counts.confusion;
  document.getElementById('countExclude').textContent=counts.exclude;
  document.getElementById('reviewSummary').textContent=`${fileName} · ${results.length}건을 매핑표와 비교했습니다. 아래 결과는 사용자 확인 전 AI 제안입니다.`;
  const body=document.getElementById('reviewBody');
  body.innerHTML=results.length?results.slice(0,100).map(({row,result})=>{const no=pick(row,['결의번호','rsolNo','전표번호'])||'-';const vendor=pick(row,['거래처명','거래처'])||'-';const amount=originalAmount(row);const detail=pick(row,['결의상세','세부내역','세부항목명'])||'-';const cls=result.type==='cost'?'cost':result.type==='asset'?'asset':result.type==='exclude'?'hold':'confusion';return `<tr><td>${esc(no)}</td><td>${esc(vendor)}</td><td>₩${amount.toLocaleString('ko-KR')}</td><td>${esc(detail)}</td><td><span class="badge ${cls}">${esc(result.label)}</span></td><td>${esc(result.reason)}</td></tr>`}).join(''):'<tr><td colspan="6" class="empty-row">읽을 수 있는 데이터 행이 없습니다.</td></tr>';
  document.getElementById('reviewPanel').classList.add('visible');
  document.getElementById('reviewPanel').scrollIntoView({behavior:'smooth',block:'start'});
}
async function showFile(input,targetId){const target=document.getElementById(targetId);if(!input.files||!input.files[0]){target.textContent='파일을 선택하거나 끌어놓으세요';return}const file=input.files[0];target.textContent='⟳ '+file.name+' 분석 중...';target.style.color='#b66c2e';try{if(typeof XLSX==='undefined')throw new Error('스프레드시트 엔진을 불러오지 못했습니다.');const data=await file.arrayBuffer();const wb=XLSX.read(data,{type:'array',cellDates:true});const ws=wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json(ws,{defval:''});target.textContent='✓ '+file.name;target.style.color='#147a52';renderResults(rows,file.name)}catch(err){target.textContent='⚠ 분석 실패: '+err.message;target.style.color='#b36262';document.getElementById('reviewPanel').classList.add('visible');document.getElementById('reviewSummary').textContent='파일을 분석하지 못했습니다. 형식과 헤더를 확인해 주세요.'}}
function resetReview(){document.getElementById('ledgerInput').value='';document.getElementById('ledgerFile').textContent='파일을 선택하거나 끌어놓으세요';document.getElementById('ledgerFile').style.color='';document.getElementById('reviewPanel').classList.remove('visible');document.getElementById('assetCenter').classList.remove('visible')}
function openAssetCenter(){const rows=latestResults.filter(x=>x.result.type==='asset');const body=document.getElementById('assetBody');body.innerHTML=rows.length?rows.map(({row,result},i)=>{const no=pick(row,['결의번호','rsolNo','전표번호'])||'-';const vendor=pick(row,['거래처명','거래처'])||'-';const amount=originalAmount(row);return `<tr><td>${esc(no)}</td><td>${esc(vendor)}</td><td>₩${amount.toLocaleString('ko-KR')}</td><td><span class="badge asset">${esc(result.label)}</span></td><td><select data-row="${i}" onchange="setReply(${i},this.value)"><option value="">선택</option><option value="자산등재">자산등재</option><option value="비용처리">비용처리</option></select></td></tr>`}).join(''):'<tr><td colspan="5" class="empty-row">자산으로 분류된 검토 대상이 없습니다.</td></tr>';document.getElementById('assetCenter').classList.add('visible');document.getElementById('assetCenter').scrollIntoView({behavior:'smooth',block:'start'})}
function assetRows(){return latestResults.filter(x=>x.result.type==='asset')}
function setReply(i,value){const rows=assetRows();if(rows[i])rows[i].final=value}
function mailText(){const rows=assetRows();return `자산담당자님께!\n\n선급금 계정과목 검토 중 용역완료 후 자산등재 가능성이 있는 목록 및 관련문서를 붙임으로 송부드립니다.\n자산등재여부 검토결과를 1월5일까지 회신하여 주시기 바랍니다.\n\n검토 대상: ${rows.length}건\n\n감사합니다.`}
async function copyMailDraft(){const text=mailText();try{await navigator.clipboard.writeText(text);document.getElementById('copyStatus').textContent='메일 초안을 클립보드에 복사했습니다.'}catch{document.getElementById('copyStatus').textContent='복사할 수 없습니다. 화면의 초안을 직접 복사해 주세요.'}}
function downloadAssetList(){const rows=assetRows();const headerSet=new Set();rows.forEach(({row})=>Object.keys(row).forEach(k=>headerSet.add(k)));const originalHeaders=[...headerSet];const headers=[...originalHeaders,'AI제안'];const data=rows.map(({row,result})=>{const out={};originalHeaders.forEach(h=>out[h]=row[h]??'');out['AI제안']=result.label;return out});const ws=XLSX.utils.json_to_sheet(data,{header:headers});ws['!autofilter']={ref:ws['!ref']};ws['!freeze']={xSplit:0,ySplit:1};ws['!cols']=headers.map(h=>({wch:Math.max(12,Math.min(28,String(h).length+4))}));applyAmountFormat(ws);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'자산등재여부 검토목록');XLSX.writeFile(wb,'자산등재여부_검토목록.xlsx')}
function saveFinal(){const missing=assetRows().filter(x=>!x.final);if(missing.length){alert(`${missing.length}건의 담당자 회신이 남아 있습니다.`);return}document.querySelector('#assetCenter .status-chip').textContent='최종값 저장 완료';buildJournal();document.getElementById('journalPanel').classList.add('visible');document.getElementById('journalPanel').scrollIntoView({behavior:'smooth',block:'start'})}
function finalReviewLabel(item){const {result}=item;const final=item.final;if(result.type==='exclude')return '대상제외';if(result.type==='cost')return '비용';if(result.type==='asset')return final==='비용처리'?'비용':final==='자산등재'?'자산':'미회신';if(result.type==='confusion')return final==='비용처리'?'비용':final==='자산등재'?'자산':'분류혼선';return result.label||''}
function downloadClassificationResult(){if(!latestResults.length){alert('먼저 원장을 업로드하고 검토 결과를 생성해 주세요.');return}const missing=assetRows().filter(x=>!x.final);if(missing.length){alert(`${missing.length}건의 담당자 회신을 먼저 입력해 주세요.`);return}const order={비용:1,자산:2,대상제외:3,분류혼선:4};const rows=latestResults.map(item=>{const {row,result}=item;const out={};const finalLabel=finalReviewLabel(item);const remapped=finalLabel==='비용'&&result.type==='asset'?findMappedAccount(row):null;REVIEW_HEADERS.forEach(h=>out[h]=row[h]??'');out['검토결과']=finalLabel;const accountCode=result.accountCode||remapped?.accountCode||'';const accountName=result.accountName||remapped?.accountName||'';if(accountCode&&!out['계정과목코드'])out['계정과목코드']=accountCode;if(accountName&&!out['계정과목명'])out['계정과목명']=accountName;return out}).sort((a,b)=>(order[a['검토결과']]||99)-(order[b['검토결과']]||99));const ws=XLSX.utils.json_to_sheet(rows,{header:REVIEW_HEADERS});ws['!autofilter']={ref:ws['!ref']};ws['!freeze']={xSplit:0,ySplit:1};ws['!cols']=REVIEW_HEADERS.map(h=>({wch:Math.max(12,Math.min(28,String(h).length+4))}));applyAmountFormat(ws);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'선급금 계정_분류결과');XLSX.writeFile(wb,'선급금 계정_분류결과.xlsx')}
function buildJournal(){const rows=latestResults.filter(x=>x.result.type==='cost'||x.final==='자산등재'||x.final==='비용처리').flatMap(({row,result,final})=>{const amount=money(pick(row,['차변','금액','차변금액','대변금액']));const no=pick(row,['결의번호','rsolNo','전표번호'])||'-';const project=pick(row,['사업ID','사업ID명','사업']);const vendor=pick(row,['거래처명','거래처']);const detail=pick(row,['결의상세','세부내역','세부항목명']);const remapped=final==='비용처리'&&result.type==='asset'?findMappedAccount(row):null;const account=result.type==='cost'?(result.accountName||'매핑 계정과목'):(final==='자산등재'?'건설중인자산':remapped?.accountName||'비용 계정 확인 필요');const code=result.type==='cost'?(result.accountCode||''):(final==='자산등재'?'':remapped?.accountCode||'');const source={상태:final||'비용',계정과목명:'선급금',계정과목코드:'11111',차대구분:'대변',차변금액:0,대변금액:amount,사업ID:project,세부내역:detail,거래처명:vendor,rsolNo:no};const target={상태:final||'비용',계정과목명:account,계정과목코드:code,차대구분:'차변',차변금액:amount,대변금액:0,사업ID:project,세부내역:detail,거래처명:vendor,rsolNo:no};return [source,target].map(v=>Object.fromEntries(JOURNAL_HEADERS.map(h=>[h,v[h]??''])))});const body=document.getElementById('journalBody');body.innerHTML=rows.length?rows.map(r=>`<tr><td>${esc(r.상태)}</td><td>${esc(r.계정과목명)}</td><td>${esc(r.계정과목코드)}</td><td>${r.차대구분}</td><td>₩${money(r.차변금액).toLocaleString('ko-KR')}</td><td>₩${money(r.대변금액).toLocaleString('ko-KR')}</td><td>${esc(r.사업ID)}</td><td>${esc(r.rsolNo)}</td></tr>`).join(''):'<tr><td colspan="8" class="empty-row">전표로 변환할 확정 항목이 없습니다.</td></tr>';const debit=rows.reduce((s,r)=>s+money(r.차변금액),0);const credit=rows.reduce((s,r)=>s+money(r.대변금액),0);document.getElementById('journalBalance').textContent=`차변 합계 ₩${debit.toLocaleString('ko-KR')} · 대변 합계 ₩${credit.toLocaleString('ko-KR')} · ${debit===credit?'차대 일치':'차대 확인 필요'}`;window.JOURNAL_ROWS=rows}
function applyAmountFormat(ws){const range=XLSX.utils.decode_range(ws['!ref']||'A1');const amountCols=[];for(let c=range.s.c;c<=range.e.c;c++){const v=ws[XLSX.utils.encode_cell({r:range.s.r,c})]?.v;if(['차변금액','대변금액','차변','대변'].includes(v))amountCols.push(c)}for(const c of amountCols){for(let r=range.s.r+1;r<=range.e.r;r++){const cell=ws[XLSX.utils.encode_cell({r,c})];if(cell)cell.z='#,##0'}}}
function downloadJournalXlsx(){if(!window.JOURNAL_ROWS?.length){alert('먼저 최종값을 저장해 주세요.');return}const order={비용:1,자산:2,대상제외:3,분류혼선:4};const exportHeaders=JOURNAL_HEADERS;const exportRows=window.JOURNAL_ROWS.slice().sort((a,b)=>(order[a.상태]||99)-(order[b.상태]||99)).map(row=>Object.fromEntries(exportHeaders.map(h=>[h,h==='상태'?'':row[h]??''])));const ws=XLSX.utils.json_to_sheet(exportRows,{header:exportHeaders});ws['!autofilter']={ref:ws['!ref']};ws['!freeze']={xSplit:0,ySplit:1};ws['!cols']=exportHeaders.map((h,i)=>({wch:i>=1&&i<9?Math.max(12,Math.min(24,String(h).length+4)):12,hidden:i===0||i>=9}));applyAmountFormat(ws);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'선급금 비용대체');XLSX.writeFile(wb,'결산조정_F선급금T비용.xlsx',{cellStyles:true})}
function downloadJournalMd(){if(!window.JOURNAL_ROWS?.length){alert('먼저 최종값을 저장해 주세요.');return}const rows=window.JOURNAL_ROWS;const md=['# 결산조정대체전표_선급금','','| 상태 | 계정과목명 | 계정과목 | 차대구분 | 차변금액 | 대변금액 | 사업명 | 결의번호 |','|---|---|---|---|---:|---:|---|---|',...rows.map(r=>`| ${r.상태} | ${r.계정과목명} | ${r.계정과목코드} | ${r.차대구분} | ${r.차변금액} | ${r.대변금액} | ${r.사업ID} | ${r.rsolNo} |`)].join('\n');const blob=new Blob([md],{type:'text/markdown;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='결산조정_F선금금T비용.md';a.click();URL.revokeObjectURL(a.href)}
function openReversal(){if(!window.JOURNAL_ROWS?.length){alert('먼저 조정전표 초안을 생성해 주세요.');return}const counts=new Map();window.JOURNAL_ROWS.forEach(r=>{const id=r.사업ID||'-';counts.set(id,(counts.get(id)||0)+1)});window.REVERSAL_PROJECTS=[...counts.keys()];const body=document.getElementById('reversalBody');body.innerHTML=window.REVERSAL_PROJECTS.map((id,i)=>`<tr><td>${esc(id)}</td><td class="center"><select data-project-reversal="${i}"><option value="N" selected>종료사업</option><option value="Y">계속사업</option></select></td></tr>`).join('');document.getElementById('reversalPanel').classList.add('visible');document.getElementById('reversalPanel').scrollIntoView({behavior:'smooth',block:'start'})}
function buildReversal(){const selects=[...document.querySelectorAll('[data-project-reversal]')];if(!selects.length){alert('환원 대상 사업이 없습니다.');return}const decisions=new Map(selects.map(s=>[window.REVERSAL_PROJECTS[Number(s.dataset.projectReversal)],s.value]));window.REVERSAL_ROWS=window.JOURNAL_ROWS.map(r=>{const decision=decisions.get(r.사업ID||'-');return {...r,사업ID:decision==='Y'?(r.사업ID||'-'):'25-10-A-11',차대구분:r.차대구분==='차변'?'대변':'차변',차변금액:r.대변금액,대변금액:r.차변금액}});document.getElementById('reversalResult').textContent=`${window.REVERSAL_ROWS.length}건의 환원전표 초안이 생성되었습니다. 사업별 구분과 반대분개를 확인한 후 다운로드하세요.`;document.querySelector('#reversalPanel .status-chip').textContent='초안 생성 완료'}
function downloadReversalXlsx(){if(!window.REVERSAL_ROWS?.length){alert('먼저 구분을 선택하고 환원전표를 생성해 주세요.');return}const exportHeaders=JOURNAL_HEADERS;const exportRows=window.REVERSAL_ROWS.map(row=>Object.fromEntries(exportHeaders.map(h=>[h,h==='상태'?'':row[h]??''])));const ws=XLSX.utils.json_to_sheet(exportRows,{header:exportHeaders});ws['!autofilter']={ref:ws['!ref']};ws['!freeze']={xSplit:0,ySplit:1};ws['!cols']=exportHeaders.map((h,i)=>({wch:i>=1&&i<9?Math.max(12,Math.min(24,String(h).length+4)):12,hidden:i===0||i>=9}));applyAmountFormat(ws);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'전기이월');XLSX.writeFile(wb,'전기이월_F비용T선급금.xlsx',{cellStyles:true})}
function downloadReversalMd(){if(!window.REVERSAL_ROWS?.length){alert('먼저 환원전표를 생성해 주세요.');return}const rows=window.REVERSAL_ROWS;const md=['# 전기이월_F비용T선급금','','| 상태 | 사업ID | 계정과목명 | 계정과목 | 차대구분 | 차변금액 | 대변금액 | 결의번호 |','|---|---|---|---|---|---:|---:|---|',...rows.map(r=>`| ${r.상태} | ${r.사업ID} | ${r.계정과목명} | ${r.계정과목코드} | ${r.차대구분} | ${r.차변금액} | ${r.대변금액} | ${r.rsolNo} |`)].join('\n');const blob=new Blob([md],{type:'text/markdown;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='전기이월_F비용T선급금.md';a.click();URL.revokeObjectURL(a.href)}
const initialView=location.hash==='#standards'?'standards':'dashboard';history.replaceState({arcView:initialView},'',`${location.pathname}${location.search}${initialView==='standards'?'#standards':''}`);if(initialView==='standards')applyView('standards');
