const STANDARD_CHANGES=[{kind:'당기 시행',standard:'K-IFRS 2021-2023 연차개선',summary:'현금흐름표·최초채택·금융상품 등 관련 기준 개정',announced:'2024-11-22',effective:'2026-01-01',status:'적용 확인 필요',url:'https://www.kasb.or.kr/front/board/List2006.do'},{kind:'당기 시행',standard:'금융상품의 분류와 측정 개정',summary:'금융상품 분류·측정 및 공시 관련 개정',announced:'2024-11-22',effective:'2026-01-01',status:'적용 확인 필요',url:'https://www.kasb.or.kr/front/board/List2006.do'},{kind:'당기 시행',standard:'교환가능성 결여',summary:'외화 환산 시 교환가능성 판단 관련 개정',announced:'2023-12-22',effective:'2026-01-01',status:'관련성 검토',url:'https://www.kasb.or.kr/front/board/List2006.do'},{kind:'향후 시행',standard:'K-IFRS 제1118호 재무제표 표시와 공시',summary:'재무제표 표시 및 공시 체계 변경',announced:'2025-11-21',effective:'2027-01-01',status:'사전 검토',url:'https://www.kasb.or.kr/front/board/List2006.do'}];
STANDARD_CHANGES.forEach(r=>{r.basis='K-IFRS|공기업·준정부기관 회계기준'});
function standardKindForYear(row,year){return year==='2027'&&row.effective.startsWith('2027')?'당기 시행':year==='2026'&&row.effective.startsWith('2027')?'향후 시행':row.kind}
function resetStandardStats(){document.getElementById('stdEffective').textContent='—';document.getElementById('stdFuture').textContent='—';document.getElementById('stdNeed').textContent='—';document.getElementById('standardsBody').innerHTML='<tr><td colspan="7" class="empty-row">결산연도와 적용기준을 선택한 후 변경사항 조회를 눌러 주세요.</td></tr>'}
function updateStandardStats(rows,year){const effective=rows.filter(r=>standardKindForYear(r,year)==='당기 시행').length;const future=rows.filter(r=>standardKindForYear(r,year)==='향후 시행').length;const need=rows.filter(r=>r.status.includes('확인')||r.status==='관련성 검토').length;document.getElementById('stdEffective').textContent=effective;document.getElementById('stdFuture').textContent=future;document.getElementById('stdNeed').textContent=need}
function applyStage(stage,scroll=false){const review=document.getElementById('reviewPanel');const asset=document.getElementById('assetCenter');const journal=document.getElementById('journalPanel');const reversal=document.getElementById('reversalPanel');[review,asset,journal,reversal].forEach(el=>el.classList.remove('visible'));if(stage!=='dashboard'){review.classList.add('visible');if(stage==='asset'||stage==='journal'||stage==='reversal')asset.classList.add('visible');if(stage==='journal'||stage==='reversal')journal.classList.add('visible');if(stage==='reversal')reversal.classList.add('visible')}if(scroll){const target=stage==='asset'?asset:stage==='journal'?journal:stage==='reversal'?reversal:stage==='review'?review:document.getElementById('dashboard');target?.scrollIntoView({behavior:'smooth',block:'start'})}}
function pushStage(stage){if(history.state?.arcStage!==stage){history.pushState({arcView:'dashboard',arcStage:stage},'',`${location.pathname}${location.search}#${stage}`)}}
function applyView(view){const dashboard=document.getElementById('dashboard');const standards=document.getElementById('standardsPanel');const aiDeep=document.getElementById('aiDeepPanel');if(view==='standards'){dashboard.style.display='none';aiDeep.classList.remove('visible');standards.classList.add('visible');resetStandardStats()}else if(view==='aiDeep'){dashboard.style.display='none';standards.classList.remove('visible');aiDeep.classList.add('visible')}else{standards.classList.remove('visible');aiDeep.classList.remove('visible');dashboard.style.display='block';applyStage('dashboard')}}
function openAiDeepAnalysis(fromHistory=false){if(!fromHistory&&history.state?.arcView!=='aiDeep'){history.pushState({arcView:'aiDeep'},'',`${location.pathname}${location.search}#ai-deep`)}applyView('aiDeep')}
function closeAiDeepAnalysis(){openDashboardHome()}
function openStandards(fromHistory=false){if(!fromHistory&&history.state?.arcView!=='standards'){history.pushState({arcView:'standards'},'',`${location.pathname}${location.search}#standards`)}applyView('standards')}
function closeStandards(){openDashboardHome()}
window.addEventListener('popstate',event=>{if(event.state?.arcView==='standards')applyView('standards');else if(event.state?.arcView==='aiDeep')applyView('aiDeep');else if(event.state?.account)selectAccount(event.state.account,true);else if(event.state?.arcStage&&event.state.arcStage!=='dashboard'){selectAccount('선급금',true);applyStage(event.state.arcStage,true)}else openDashboardHome(true)})
function downloadGuideline(event,path,filename){event.preventDefault();event.stopPropagation();const status=document.getElementById('guidelineStatus');if(status)status.textContent='업무처리지침 파일을 저장하는 중입니다...';fetch(path).then(response=>{if(!response.ok)throw new Error(`파일을 불러오지 못했습니다 (${response.status})`);return response.blob()}).then(blob=>{const objectUrl=URL.createObjectURL(blob);const link=document.createElement('a');link.href=objectUrl;link.download=filename;link.style.display='none';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(objectUrl),1000);if(status)status.textContent='파일 저장을 시작했습니다. ARC 화면은 유지됩니다.'}).catch(error=>{if(status){status.textContent=`파일 저장 실패: ${error.message}`;status.classList.add('source-warning')}});return false}
function openSource(event,url){event.stopPropagation();history.replaceState({arcView:'standards',arcSourceReturn:true},'',`${location.pathname}${location.search}#standards`);const status=document.getElementById('sourceStatus');if(status){status.classList.remove('source-warning');status.textContent='원문 링크를 새 탭으로 열었습니다. ARC 화면은 현재 탭에 유지됩니다.'}return true}
function renderStandards(rows){const selectedBasis=document.getElementById('standardsBasis')?.value;const selectedYear=document.getElementById('standardsYear')?.value;updateStandardStats(rows,selectedYear);const body=rows.length?rows.map(r=>`<tr><td><span class="badge ${standardKindForYear(r,selectedYear)==='당기 시행'?'cost':'asset'}">${standardKindForYear(r,selectedYear)}</span></td><td>${esc(r.standard)}</td><td>${esc(r.summary)}</td><td>${r.announced}</td><td>${r.effective}</td><td>${esc(selectedBasis==='공기업·준정부기관 회계기준'?'기관 적용 여부 확인':r.status)}</td><td><a class="source-link" href="${esc(r.url)}" target="_blank" rel="noopener noreferrer" onclick="return openSource(event,this.href)">원문 확인 ↗</a></td></tr>`).join(''):`<tr><td colspan="7" class="empty-row">선택한 적용기준에 연결된 변경자료가 없습니다. 공식 원문과 기관 적용기준을 확인해 주세요.</td></tr>`;document.getElementById('standardsBody').innerHTML=body}
function filterStandards(){const year=document.getElementById('standardsYear').value;const yearMatches=r=>year==='2026'||r.effective.startsWith(year);renderStandards(STANDARD_CHANGES.filter(r=>yearMatches(r)));}
function parseAiJson(text){const raw=String(text||'').trim();const cleaned=raw.replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'').trim();try{return JSON.parse(cleaned)}catch(firstError){const start=cleaned.indexOf('{');const end=cleaned.lastIndexOf('}');if(start>=0&&end>start){try{return JSON.parse(cleaned.slice(start,end+1))}catch(secondError){}}throw new Error(`AI 응답을 JSON으로 해석하지 못했습니다: ${firstError.message}`)}}
async function review1118WithOpenAILegacy(){const key=document.getElementById('openaiApiKey')?.value.trim();const context=document.getElementById('standardAiContext')?.value.trim();const year=document.getElementById('standardsYear')?.value||'2026';const status=document.getElementById('aiReviewStatus');const resultBox=document.getElementById('aiReviewResult');if(!key){status.textContent='OpenAI API Key를 화면에 입력해 주세요. 키는 저장하지 않습니다.';status.classList.add('source-warning');return}if(!context){status.textContent='기관 적용정보를 입력해 주세요.';status.classList.add('source-warning');return}status.classList.remove('source-warning');status.textContent='OpenAI에 제1118호 적용 여부를 검토 요청 중입니다...';resultBox.hidden=true;const prompt=`당신은 공기업·준정부기관 회계담당자의 검토를 보조하는 AI입니다. 회계기준을 최종 확정하지 말고, 제공된 사실과 아래 기준자료만 근거로 검토의견을 작성하세요. 불확실한 부분은 반드시 확인 필요로 표시하세요.\n\n대상 기준서: K-IFRS 제1118호 재무제표 표시와 공시\n시행일: 2027-01-01\n선택 결산연도: ${year}\n기준자료 요약: 재무제표 표시 및 공시 체계 변경. 시행일과 기관 적용 회계기준, 조기 적용 여부를 확인해야 함.\n기관 적용정보: ${context}\n\n다음 JSON만 반환하세요. 마크다운을 사용하지 마세요.\n{"conclusion":"적용 가능성 높음|적용 가능성 낮음|확인 필요","confidence":"높음|중간|낮음","reasons":["근거 1","근거 2"],"checks":["추가 확인사항 1","추가 확인사항 2"],"disclaimer":"최종 적용 여부는 공식 기준서와 기관 회계정책을 확인해 담당자가 확정해야 함"}`;try{const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${key}`},body:JSON.stringify({model:'gpt-4o-mini',input:prompt})});const data=await response.json();if(!response.ok)throw new Error(data?.error?.message||`API 오류(${response.status})`);const text=extractAiText(data);const result=parseAiJson(text);resultBox.innerHTML=`<div class="ai-result-grid"><div><span>검토의견</span><strong>${esc(result.conclusion||'확인 필요')}</strong></div><div><span>확신도</span><strong>${esc(result.confidence||'낮음')}</strong></div></div><h4>판단 근거</h4><ul>${(result.reasons||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h4>추가 확인사항</h4><ul>${(result.checks||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p class="ai-disclaimer">${esc(result.disclaimer||'최종 판단은 담당자 확인이 필요합니다.')}</p>`;resultBox.hidden=false;status.textContent='AI 검토 의견을 받았습니다. 담당자 확인 후 최종 판단하세요.'}catch(error){status.textContent=`AI 검토 실패: ${error.message}`;status.classList.add('source-warning')}}
function extractAiText(data){if(typeof data?.output_text==='string'&&data.output_text.trim())return data.output_text;const parts=[];(data?.output||[]).forEach(item=>(item?.content||[]).forEach(part=>{if(typeof part?.text==='string')parts.push(part.text)}));return parts.join('\\n').trim()}
async function callArcAI({module,subject,context,year,reference,outputSchema,keyInputId='openaiApiKey',conversation=[],apiKey=''}){const key=apiKey||document.getElementById(keyInputId)?.value.trim();if(!key)throw new Error('첫 질문 전에 OpenAI API Key를 화면에 입력해 주세요. 키는 저장하지 않습니다.');const history=conversation.length?`\n\n이전 검토 대화:\n${conversation.map((m,i)=>`${i+1}. ${m.role==='user'?'담당자':'AI'}: ${m.content}`).join('\n')}`:'';const prompt=`당신은 공기업·준정부기관 회계담당자의 검토를 보조하는 AI입니다. 최종 회계판단을 확정하지 말고, 제공된 사실과 기준자료에 근거한 검토의견만 작성하세요. 불확실한 부분은 확인 필요로 표시하세요. 이전 대화가 있으면 그 맥락을 유지하고 이번 질문에서 새로 제시된 사실과 담당자 보완을 반영하세요.\n\n검토 모듈: ${module}\n검토 대상: ${subject}\n선택 결산연도: ${year||'미입력'}\n기준자료: ${reference}\n기관·거래 정보: ${context}${history}\n\n다음 JSON 형식만 반환하세요. 마크다운을 사용하지 마세요.\n${outputSchema}`;const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${key}`},body:JSON.stringify({model:'gpt-4o-mini',input:prompt})});const data=await response.json();if(!response.ok)throw new Error(data?.error?.message||`API 오류(${response.status})`);const text=extractAiText(data);if(!text)throw new Error('AI 응답 본문이 비어 있습니다.');return parseAiJson(text)}
function renderAiResultBox(resultBox,result){resultBox.innerHTML=`<div class="ai-result-grid"><div><span>검토의견</span><strong>${esc(result.conclusion||'확인 필요')}</strong></div><div><span>확신도</span><strong>${esc(result.confidence||'낮음')}</strong></div></div><h4>판단 근거</h4><ul>${(result.reasons||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h4>추가 확인사항</h4><ul>${(result.checks||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p class="ai-disclaimer">${esc(result.disclaimer||'최종 판단은 담당자 확인이 필요합니다.')}</p>`;resultBox.hidden=false}
let aiSessionMessages=[];let aiSessionMeta={domain:'',target:'',createdAt:''};let aiSessionKey='';
function renderConversation(){const box=document.getElementById('aiConversation');if(!box)return;if(!aiSessionMessages.length){box.style.display='none';box.innerHTML='';document.getElementById('aiSessionState').textContent='새 검토 세션';return}box.style.display='block';box.innerHTML=aiSessionMessages.map(m=>`<div class="conversation-item ${m.role==='user'?'user-turn':'assistant-turn'}"><span class="conversation-role">${m.role==='user'?'담당자':'ARC AI'}</span><div class="conversation-body">${m.role==='assistant'?formatAiAnswer(m.content):esc(m.content).replace(/\n/g,'<br>')}</div></div>`).join('');box.scrollTop=box.scrollHeight;document.getElementById('aiSessionState').textContent=`검토 중 · ${aiSessionMessages.filter(m=>m.role==='user').length}회 질문`}
function formatAiAnswer(content){if(typeof content==='object')return renderStructuredAnswer(content);return esc(content).replace(/\n/g,'<br>')}
function renderStructuredAnswer(result){return `<div class="ai-answer-conclusion"><b>${esc(result.conclusion||'검토 필요')}</b><span>확신도 ${esc(result.confidence||'낮음')}</span></div><h4>판단 근거</h4><ul>${(result.reasons||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h4>우리 기관에 미치는 영향</h4><ul>${(result.impacts||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h4>추가 확인사항</h4><ul>${(result.checks||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p class="ai-disclaimer">${esc(result.disclaimer||'AI 의견은 검토 보조자료이며 최종 판단은 담당자가 확정해야 합니다.')}</p>`}
function clearAiKey(){aiSessionKey='';document.getElementById('aiDeepApiKey').value='';document.getElementById('aiDeepStatus').textContent='API Key를 삭제했습니다. 다음 AI 요청 전에 다시 입력해 주세요.';document.getElementById('aiDeepStatus').classList.remove('source-warning')}
function clearAiSession(){aiSessionMessages=[];aiSessionMeta={domain:'',target:'',createdAt:''};document.getElementById('aiDeepQuestion').value='';document.getElementById('aiDeepEvidence').value='';document.getElementById('aiSessionState').textContent='새 검토 세션';renderConversation();document.getElementById('aiDeepStatus').textContent='새 검토 세션을 시작했습니다. API Key는 유지됩니다.'}
function aiReportMarkdown(){const target=document.getElementById('aiDeepTarget').value.trim()||aiSessionMeta.target||'미입력';const domain=document.getElementById('aiDeepDomain').value;const lines=[`# ARC AI 심층분석 검토보고서`,``,`- 분석 영역: ${domain}`,`- 분석 대상: ${target}`,`- 작성일: ${new Date().toLocaleString('ko-KR')}`,`- 상태: 담당자 최종 확인 필요`,'','## 검토 대화'];aiSessionMessages.forEach((m,i)=>{lines.push('',`### ${m.role==='user'?'담당자 질문·보완':'ARC AI 검토의견'} ${i+1}`,typeof m.content==='string'?m.content:JSON.stringify(m.content,null,2))});lines.push('','## 유의사항','본 보고서는 AI와 담당자의 대화를 정리한 검토 보조자료입니다. 공식 기준서, 기관 회계정책 및 담당자 확인 없이 최종 회계처리로 확정하지 않습니다.');return lines.join('\n')}
function downloadAiReviewReport(){if(!aiSessionMessages.length){alert('먼저 AI와 한 차례 이상 대화해 주세요.');return}const blob=new Blob([aiReportMarkdown()],{type:'text/markdown;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ARC_AI심층분석_검토보고서_${new Date().toISOString().slice(0,10)}.md`;a.click();URL.revokeObjectURL(a.href)}
async function runAiDeepAnalysis(){const domain=document.getElementById('aiDeepDomain').value;const target=document.getElementById('aiDeepTarget').value.trim();const question=document.getElementById('aiDeepQuestion').value.trim();const evidence=document.getElementById('aiDeepEvidence').value.trim();const status=document.getElementById('aiDeepStatus');if(!target||!question){status.textContent='분석 대상과 질문 또는 담당자 보완을 입력해 주세요.';status.classList.add('source-warning');return}if(!aiSessionKey){aiSessionKey=document.getElementById('aiDeepApiKey').value.trim()}if(!aiSessionKey){status.textContent='첫 질문 전에 OpenAI API Key를 한 번 입력해 주세요.';status.classList.add('source-warning');return}if(!aiSessionMessages.length){aiSessionMeta={domain,target,createdAt:new Date().toISOString()}}aiSessionMessages.push({role:'user',content:`질문: ${question}${evidence?`\n관련 정보·근거: ${evidence}`:''}`});renderConversation();status.classList.remove('source-warning');status.textContent='AI가 이전 대화와 이번 질문을 함께 검토 중입니다...';try{const history=aiSessionMessages.map(m=>({role:m.role==='assistant'?'assistant':'user',content:typeof m.content==='string'?m.content:JSON.stringify(m.content)}));const result=await callArcAI({module:domain,subject:target,context:`이번 질문과 관련 정보가 대화 이력에 포함되어 있습니다. 이전 답변을 반복하지 말고, 이번 질문에 답하면서 앞선 검토내용을 보완하세요.`,year:document.getElementById('standardsYear')?.value||'',reference:'공기업·준정부기관 회계담당자용 검토 보조. 기관 적용기준·공식 기준서·내부 회계정책을 우선하고, 사실이 부족하면 확인 필요로 표시.',keyInputId:'aiDeepApiKey',apiKey:aiSessionKey,conversation:history,outputSchema:'{"conclusion":"검토 결론을 한 문장으로 작성","confidence":"높음|중간|낮음","reasons":["이전 대화와 이번 질문을 반영한 판단 근거"],"impacts":["우리 기관의 재무·공시·업무 영향"],"checks":["담당자가 추가 확인할 자료나 질문"],"disclaimer":"최종 판단은 담당자 확인이 필요하다는 안내"}'});aiSessionMessages.push({role:'assistant',content:result});document.getElementById('aiDeepQuestion').value='';document.getElementById('aiDeepEvidence').value='';renderConversation();status.textContent='답변을 받았습니다. 추가 질문이나 담당자 보완을 이어가세요.'}catch(error){aiSessionMessages.pop();renderConversation();status.textContent=`AI 심층분석 실패: ${error.message}`;status.classList.add('source-warning')}}
async function review1118WithOpenAI(){const context=document.getElementById('standardAiContext')?.value.trim();const year=document.getElementById('standardsYear')?.value||'2026';const status=document.getElementById('aiReviewStatus');const resultBox=document.getElementById('aiReviewResult');if(!context){status.textContent='기관 적용정보를 입력해 주세요.';status.classList.add('source-warning');return}status.classList.remove('source-warning');status.textContent='OpenAI에 제1118호 적용 여부를 검토 요청 중입니다...';resultBox.hidden=true;try{const result=await callArcAI({module:'ifrs1118',subject:'K-IFRS 제1118호 적용 여부',year,context,reference:'K-IFRS 제1118호 재무제표 표시와 공시. 시행일 2027-01-01. 기관 적용 회계기준과 조기 적용 여부 확인 필요.',outputSchema:'{"conclusion":"적용 가능성 높음|적용 가능성 낮음|확인 필요","confidence":"높음|중간|낮음","reasons":["근거 1","근거 2"],"checks":["추가 확인사항 1","추가 확인사항 2"],"disclaimer":"최종 적용 여부는 공식 기준서와 기관 회계정책을 확인해 담당자가 확정해야 함"}'});render1118AiResult(result);status.textContent='AI 검토 의견을 받았습니다. 담당자 확인 후 최종 판단하세요.'}catch(error){status.textContent=`AI 검토 실패: ${error.message}`;status.classList.add('source-warning')}}
const ASSET_WORDS=['공사','건물','구축물','기계장치','장비','자산취득','시설','취득','소프트웨어','설계','토지'];
const EXCLUDE_WORDS=['제거','정산완료','이미 대체','환원완료'];
const REVIEW_HEADERS=['계정과목','승인일자','거래처명','결의상세','차변','대변','사업ID','비목ID','비목명','세부항목코드','세부항목명','결의부서명','결의자명','결의번호','검토결과','계정과목코드','계정과목명'];
const JOURNAL_HEADERS=['상태','계정과목명','계정과목코드','차대구분','차변금액','대변금액','사업ID','세부내역','거래처명','actsYy','bzplCd','rsolNo','bdgtBzplCd','aplDeptCd','dtalAtclCd','actrCd','actrNm','drcrDivCd2','pendMngeDivCd','pendNo','acotClssCd','evidNo','evidMngeNo','acotTyCd','mngeAtclCd1','ramtMngeYn1','mngeAtclVal1','mngeAtclValNm1','mngeAtclCd2','ramtMngeYn2','mngeAtclVal2','mngeAtclValNm2','mngeAtclCd3','ramtMngeYn3','mngeAtclVal3','mngeAtclValNm3','imgnAccnInstCd','bankCd','imgnAccnNo','imgnAccnDlngDt','imgnAccnDlngPtm','imgnAccnDlngSrno','fincAstsNo','dlngItmnSrno','계좌번호','금융자산명'];
const rowGroupKey=row=>{const vendor=pick(row,['거래처명','거래처','vendor']);const detail=pick(row,['결의상세','세부내역','세부항목명']);const project=pick(row,['사업ID','사업ID명','사업']);if(!vendor&&!detail&&!project)return '';return [vendor,detail,project].join('|')};
function pairedStates(rows){const groups=new Map();rows.forEach((row,index)=>{const key=rowGroupKey(row);if(!key)return;const g=groups.get(key)||{debit:0,credit:0,indexes:[]};g.debit+=money(pick(row,['차변','차변금액']));g.credit+=money(pick(row,['대변','대변금액']));g.indexes.push(index);groups.set(key,g)});const states=new Map();for(const g of groups.values()){if(g.debit>0&&g.credit>0){const matched=Math.abs(g.debit-g.credit)<0.5;g.indexes.forEach(i=>states.set(i,matched?'exclude':'confusion'))}}return states};
const pick=(row,names)=>{for(const n of names){if(Object.prototype.hasOwnProperty.call(row,n)&&String(row[n]).trim()!=='')return String(row[n]).trim();}const key=Object.keys(row).find(k=>names.some(n=>k.includes(n)));return key?String(row[key]??'').trim():''};
const money=v=>{const n=Number(String(v).replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0};
const originalAmount=row=>{const debit=money(pick(row,['차변','차변금액']));const credit=money(pick(row,['대변','대변금액']));const amount=money(pick(row,['금액','금액(원)']));return debit||credit||amount};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function findMappedAccount(row){const code=pick(row,['비목코드','비목ID','비목 코드','bdgtCd']);const detailCode=pick(row,['세부항목코드','세부항목 코드','dtalAtclCd']);const budget=pick(row,['비목명','비목','budgetName']);const detail=pick(row,['세부항목명','세부항목','세부내역']);const match=(window.MAPPING_TABLE||[]).find(m=>(code&&String(m['비목코드']).trim()===code)&&(detailCode&&String(m['세부항목']).trim()===detailCode))||(window.MAPPING_TABLE||[]).find(m=>String(m['비목명']??'').trim()===budget&&String(m['세부항목명']??'').trim()===detail);return match&&String(match['계정과목']??'').trim()?{accountCode:String(match['계정과목']).trim(),accountName:String(match['계정과목명']??'').trim()}:null}
function classify(row,pairState){
 const text=Object.values(row).join(' ');
 const no=pick(row,['결의번호','결의번호명','rsolNo','전표번호']);
 const vendor=pick(row,['거래처명','거래처','vendor']);
 const amount=pick(row,['금액','차변','대변','차변금액','대변금액','금액(원)']);
 const budget=pick(row,['비목명','비목','budgetName']);
 const detail=pick(row,['세부항목명','세부항목','세부내역']);
 if(pairState==='exclude') return {type:'exclude',label:'대상제외',reason:'거래처·결의상세 기준 차변·대변 선급금 금액이 상계되어 잔액 0'};
 if(pairState==='confusion') return {type:'confusion',label:'분류혼선',reason:'차변·대변 선급금 행은 연결되지만 금액이 일치하지 않아 잔액 확인 필요'};
 if(EXCLUDE_WORDS.some(w=>text.includes(w))) return {type:'exclude',label:'대상제외',reason:'원장 내용상 이미 제거·정산된 항목'};
 if(ASSET_WORDS.some(w=>text.includes(w))) return {type:'asset',label:'자산',reason:'공사·자산 관련 키워드 포함'};
 const match=findMappedAccount(row);
 if(match) return {type:'cost',label:'비용',reason:`매핑표 일치 · ${match.accountCode} ${match.accountName}`,...match};
 return {type:'confusion',label:'분류혼선',reason:'비목·세부항목 매핑 또는 차변·대변 연결 근거 확인 필요'};
}
function renderResults(rows,fileName){
  const pairStates=pairedStates(rows);
  const results=rows.map((r,i)=>({row:r,result:classify(r,pairStates.get(i))}));
  latestResults=results;
  const counts={cost:0,asset:0,confusion:0,exclude:0};results.forEach(x=>counts[x.result.type]++);
  document.getElementById('countAll').textContent=results.length;
  document.getElementById('countCost').textContent=counts.cost;
  document.getElementById('countAsset').textContent=counts.asset;
  document.getElementById('countHold').textContent=counts.confusion;
  document.getElementById('countExclude').textContent=counts.exclude;
  document.getElementById('reviewSummary').textContent=`${fileName} · ${results.length}건을 매핑표와 비교했습니다. 아래 결과는 사용자 확인 전 AI 제안입니다.`;
  const body=document.getElementById('reviewBody');
  body.innerHTML=results.length?results.slice(0,100).map(({row,result})=>{const no=pick(row,['결의번호','rsolNo','전표번호'])||'-';const vendor=pick(row,['거래처명','거래처'])||'-';const amount=originalAmount(row);const detail=pick(row,['결의상세','세부내역','세부항목명'])||'-';const cls=result.type==='cost'?'cost':result.type==='asset'?'asset':result.type==='exclude'?'hold':'confusion';return `<tr><td>${esc(no)}</td><td>${esc(vendor)}</td><td class="num">${amount.toLocaleString('ko-KR')}</td><td>${esc(detail)}</td><td><span class="badge ${cls}">${esc(result.label)}</span></td><td>${esc(result.reason)}</td></tr>`}).join(''):'<tr><td colspan="6" class="empty-row">읽을 수 있는 데이터 행이 없습니다.</td></tr>';
  document.getElementById('reviewPanel').classList.add('visible');
  pushStage('review');
  document.getElementById('reviewPanel').scrollIntoView({behavior:'smooth',block:'start'});
}
async function showFile(input,targetId){const target=document.getElementById(targetId);if(!input.files||!input.files[0]){target.textContent='파일을 선택하거나 끌어놓으세요';return}const file=input.files[0];target.textContent='⟳ '+file.name+' 분석 중...';target.style.color='#b66c2e';try{if(typeof XLSX==='undefined')throw new Error('스프레드시트 엔진을 불러오지 못했습니다.');const data=await file.arrayBuffer();const wb=XLSX.read(data,{type:'array',cellDates:true});const ws=wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json(ws,{defval:''});target.textContent='✓ '+file.name;target.style.color='#147a52';renderResults(rows,file.name)}catch(err){target.textContent='⚠ 분석 실패: '+err.message;target.style.color='#b36262';document.getElementById('reviewPanel').classList.add('visible');document.getElementById('reviewSummary').textContent='파일을 분석하지 못했습니다. 형식과 헤더를 확인해 주세요.'}}
function resetReview(){document.getElementById('ledgerInput').value='';document.getElementById('ledgerFile').textContent='파일을 선택하거나 끌어놓으세요';document.getElementById('ledgerFile').style.color='';applyStage('dashboard');history.replaceState({arcView:'dashboard',arcStage:'dashboard'},'',`${location.pathname}${location.search}`)}
function openAssetCenter(){pushStage('asset');const rows=latestResults.filter(x=>x.result.type==='asset');const body=document.getElementById('assetBody');body.innerHTML=rows.length?rows.map(({row,result},i)=>{const no=pick(row,['결의번호','rsolNo','전표번호'])||'-';const vendor=pick(row,['거래처명','거래처'])||'-';const amount=originalAmount(row);return `<tr><td>${esc(no)}</td><td>${esc(vendor)}</td><td class="num">${amount.toLocaleString('ko-KR')}</td><td><span class="badge asset">${esc(result.label)}</span></td><td><select data-row="${i}" onchange="setReply(${i},this.value)"><option value="">선택</option><option value="자산등재">자산등재</option><option value="비용처리">비용처리</option></select></td></tr>`}).join(''):'<tr><td colspan="5" class="empty-row">자산으로 분류된 검토 대상이 없습니다.</td></tr>';document.getElementById('assetCenter').classList.add('visible');document.getElementById('assetCenter').scrollIntoView({behavior:'smooth',block:'start'})}
function assetRows(){return latestResults.filter(x=>x.result.type==='asset')}
function setReply(i,value){const rows=assetRows();if(rows[i])rows[i].final=value}
function mailText(){const rows=assetRows();return `자산담당자님께

안녕하세요.

선급금 계정과목 검토 중 용역완료 후 자산등재 가능성이 있는 목록 및 관련문서를 붙임으로 송부드립니다.

결의번호를 통해 관련 문서를 검토하신 후 자산등재 여부를 회신하여 주시기 바랍니다.

검토 대상: ${rows.length}건

감사합니다.`}
async function copyMailDraft(){const text=mailText();try{await navigator.clipboard.writeText(text);document.getElementById('copyStatus').textContent='메일 초안을 클립보드에 복사했습니다.'}catch{document.getElementById('copyStatus').textContent='복사할 수 없습니다. 화면의 초안을 직접 복사해 주세요.'}}
function downloadAssetList(){const rows=assetRows();const headerSet=new Set();rows.forEach(({row})=>Object.keys(row).forEach(k=>headerSet.add(k)));const originalHeaders=[...headerSet];const headers=[...originalHeaders,'AI제안'];const data=rows.map(({row,result})=>{const out={};originalHeaders.forEach(h=>out[h]=row[h]??'');out['AI제안']=result.label;return out});const ws=XLSX.utils.json_to_sheet(data,{header:headers});ws['!autofilter']={ref:ws['!ref']};ws['!freeze']={xSplit:0,ySplit:1};ws['!cols']=headers.map(h=>({wch:Math.max(12,Math.min(28,String(h).length+4))}));applyAmountFormat(ws);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'자산등재여부 검토목록');XLSX.writeFile(wb,'자산등재여부_검토목록.xlsx')}
function saveFinal(){const missing=assetRows().filter(x=>!x.final);if(missing.length){alert(`${missing.length}건의 담당자 회신이 남아 있습니다.`);return}document.querySelector('#assetCenter .status-chip').textContent='최종값 저장 완료';buildJournal();pushStage('journal');document.getElementById('journalPanel').classList.add('visible');document.getElementById('journalPanel').scrollIntoView({behavior:'smooth',block:'start'})}
function finalReviewLabel(item){const {result}=item;const final=item.final;if(result.type==='exclude')return '대상제외';if(result.type==='cost')return '비용';if(result.type==='asset')return final==='비용처리'?'비용':final==='자산등재'?'자산':'미회신';if(result.type==='confusion')return final==='비용처리'?'비용':final==='자산등재'?'자산':'분류혼선';return result.label||''}
function downloadClassificationResult(){if(!latestResults.length){alert('먼저 원장을 업로드하고 검토 결과를 생성해 주세요.');return}const missing=assetRows().filter(x=>!x.final);if(missing.length){alert(`${missing.length}건의 담당자 회신을 먼저 입력해 주세요.`);return}const order={비용:1,자산:2,대상제외:3,분류혼선:4};const rows=latestResults.map(item=>{const {row,result}=item;const out={};const finalLabel=finalReviewLabel(item);const remapped=finalLabel==='비용'&&result.type==='asset'?findMappedAccount(row):null;REVIEW_HEADERS.forEach(h=>out[h]=row[h]??'');out['검토결과']=finalLabel;const accountCode=finalLabel==='자산'?'22222':result.accountCode||remapped?.accountCode||'';const accountName=finalLabel==='자산'?'건설중인자산':result.accountName||remapped?.accountName||'';if(accountCode&&!out['계정과목코드'])out['계정과목코드']=accountCode;if(accountName&&!out['계정과목명'])out['계정과목명']=accountName;return out}).sort((a,b)=>(order[a['검토결과']]||99)-(order[b['검토결과']]||99));const ws=XLSX.utils.json_to_sheet(rows,{header:REVIEW_HEADERS});ws['!autofilter']={ref:ws['!ref']};ws['!freeze']={xSplit:0,ySplit:1};ws['!cols']=REVIEW_HEADERS.map(h=>({wch:Math.max(12,Math.min(28,String(h).length+4))}));applyAmountFormat(ws);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'선급금 계정_분류결과');XLSX.writeFile(wb,'선급금 계정_분류결과.xlsx')}
function buildJournal(){const rows=latestResults.filter(x=>x.result.type==='cost'||x.final==='자산등재'||x.final==='비용처리').flatMap(({row,result,final})=>{const amount=money(pick(row,['차변','금액','차변금액','대변금액']));const no=pick(row,['결의번호','rsolNo','전표번호'])||'-';const project=pick(row,['사업ID','사업ID명','사업']);const vendor=pick(row,['거래처명','거래처']);const detail=pick(row,['결의상세','세부내역','세부항목명']);const remapped=final==='비용처리'&&result.type==='asset'?findMappedAccount(row):null;const account=result.type==='cost'?(result.accountName||'매핑 계정과목'):(final==='자산등재'?'건설중인자산':remapped?.accountName||'비용 계정 확인 필요');const code=result.type==='cost'?(result.accountCode||''):(final==='자산등재'?'':remapped?.accountCode||'');const resolvedAccount=final==='자산등재'?{accountCode:'22222',accountName:'건설중인자산'}:{accountCode:code,accountName:account};const source={상태:final||'비용',계정과목명:'선급금',계정과목코드:'11111',차대구분:'대변',차변금액:0,대변금액:amount,사업ID:project,세부내역:detail,거래처명:vendor,rsolNo:no};const target={상태:final||'비용',계정과목명:resolvedAccount.accountName,계정과목코드:resolvedAccount.accountCode,차대구분:'차변',차변금액:amount,대변금액:0,사업ID:project,세부내역:detail,거래처명:vendor,rsolNo:no};return [source,target].map(v=>({...Object.fromEntries(JOURNAL_HEADERS.map(h=>[h,v[h]??''])),__sourceRow:row}))});const body=document.getElementById('journalBody');body.innerHTML=rows.length?rows.map(r=>`<tr><td>${esc(r.상태)}</td><td>${esc(r.계정과목명)}</td><td>${esc(r.계정과목코드)}</td><td>${r.차대구분}</td><td class="num">${money(r.차변금액).toLocaleString('ko-KR')}</td><td class="num">${money(r.대변금액).toLocaleString('ko-KR')}</td><td>${esc(r.사업ID)}</td><td>${esc(r.rsolNo)}</td></tr>`).join(''):'<tr><td colspan="8" class="empty-row">전표로 변환할 확정 항목이 없습니다.</td></tr>';const debit=rows.reduce((s,r)=>s+money(r.차변금액),0);const credit=rows.reduce((s,r)=>s+money(r.대변금액),0);document.getElementById('journalBalance').textContent=`차변 합계 ${debit.toLocaleString('ko-KR')} · 대변 합계 ${credit.toLocaleString('ko-KR')} · ${debit===credit?'차대 일치':'차대 확인 필요'}`;window.JOURNAL_ROWS=rows}
function applyAmountFormat(ws){const range=XLSX.utils.decode_range(ws['!ref']||'A1');const amountCols=[];for(let c=range.s.c;c<=range.e.c;c++){const v=ws[XLSX.utils.encode_cell({r:range.s.r,c})]?.v;if(['차변금액','대변금액','차변','대변'].includes(v))amountCols.push(c)}for(const c of amountCols){for(let r=range.s.r+1;r<=range.e.r;r++){const cell=ws[XLSX.utils.encode_cell({r,c})];if(cell)cell.z='#,##0'}}}
function downloadJournalXlsx(){if(!window.JOURNAL_ROWS?.length){alert('먼저 최종값을 저장해 주세요.');return}const order={비용:1,자산:2,대상제외:3,분류혼선:4};const exportHeaders=JOURNAL_HEADERS;const exportRows=window.JOURNAL_ROWS.slice().sort((a,b)=>(order[a.상태]||99)-(order[b.상태]||99)).map(row=>Object.fromEntries(exportHeaders.map(h=>[h,h==='상태'?'':row[h]??''])));const ws=XLSX.utils.json_to_sheet(exportRows,{header:exportHeaders});ws['!autofilter']={ref:ws['!ref']};ws['!freeze']={xSplit:0,ySplit:1};ws['!cols']=exportHeaders.map((h,i)=>({wch:i>=1&&i<9?Math.max(12,Math.min(24,String(h).length+4)):12,hidden:i===0||i>=9}));applyAmountFormat(ws);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'선급금 비용대체');XLSX.writeFile(wb,'결산조정_F선급금T비용.xlsx',{cellStyles:true})}
function downloadJournalMd(){if(!window.JOURNAL_ROWS?.length){alert('먼저 최종값을 저장해 주세요.');return}const rows=window.JOURNAL_ROWS;const md=['# 결산조정대체전표_선급금','','| 상태 | 계정과목명 | 계정과목 | 차대구분 | 차변금액 | 대변금액 | 사업명 | 결의번호 |','|---|---|---|---|---:|---:|---|---|',...rows.map(r=>`| ${r.상태} | ${r.계정과목명} | ${r.계정과목코드} | ${r.차대구분} | ${r.차변금액} | ${r.대변금액} | ${r.사업ID} | ${r.rsolNo} |`)].join('\n');const blob=new Blob([md],{type:'text/markdown;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='결산조정_F선금금T비용.md';a.click();URL.revokeObjectURL(a.href)}
function openReversal(){if(!window.JOURNAL_ROWS?.length){alert('먼저 조정전표 초안을 생성해 주세요.');return}pushStage('reversal');const counts=new Map();window.JOURNAL_ROWS.forEach(r=>{const id=r.사업ID||'-';counts.set(id,(counts.get(id)||0)+1)});window.REVERSAL_PROJECTS=[...counts.keys()];const body=document.getElementById('reversalBody');body.innerHTML=window.REVERSAL_PROJECTS.map((id,i)=>`<tr><td>${esc(id)}</td><td class="center"><select data-project-reversal="${i}"><option value="N" selected>종료사업</option><option value="Y">계속사업</option></select></td></tr>`).join('');document.getElementById('reversalPanel').classList.add('visible');document.getElementById('reversalPanel').scrollIntoView({behavior:'smooth',block:'start'})}
function buildReversal(){const selects=[...document.querySelectorAll('[data-project-reversal]')];if(!selects.length){alert('환원 대상 사업이 없습니다.');return}const decisions=new Map(selects.map(s=>[window.REVERSAL_PROJECTS[Number(s.dataset.projectReversal)],s.value]));window.REVERSAL_ROWS=window.JOURNAL_ROWS.map(r=>{const decision=decisions.get(r.사업ID||'-');const reversed={...r,사업ID:decision==='Y'?(r.사업ID||'-'):'25-10-A-11',차대구분:r.차대구분==='차변'?'대변':'차변',차변금액:r.대변금액,대변금액:r.차변금액};if(r.계정과목코드==='22222'||r.계정과목명==='건설중인자산'){if(reversed.차대구분==='대변'){const mapped=findMappedAccount(r.__sourceRow||{});if(mapped){reversed.계정과목코드=mapped.accountCode;reversed.계정과목명=mapped.accountName}else{reversed.계정과목코드='';reversed.계정과목명='매핑 확인 필요'}}}return reversed});document.getElementById('reversalResult').textContent=`${window.REVERSAL_ROWS.length}건의 환원전표 초안이 생성되었습니다. 사업별 구분과 반대분개를 확인한 후 다운로드하세요.`;document.querySelector('#reversalPanel .status-chip').textContent='초안 생성 완료'}
function downloadReversalXlsx(){if(!window.REVERSAL_ROWS?.length){alert('먼저 구분을 선택하고 환원전표를 생성해 주세요.');return}const exportHeaders=JOURNAL_HEADERS;const exportRows=window.REVERSAL_ROWS.map(row=>Object.fromEntries(exportHeaders.map(h=>[h,h==='상태'?'':row[h]??''])));const ws=XLSX.utils.json_to_sheet(exportRows,{header:exportHeaders});ws['!autofilter']={ref:ws['!ref']};ws['!freeze']={xSplit:0,ySplit:1};ws['!cols']=exportHeaders.map((h,i)=>({wch:i>=1&&i<9?Math.max(12,Math.min(24,String(h).length+4)):12,hidden:i===0||i>=9}));applyAmountFormat(ws);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'전기이월');XLSX.writeFile(wb,'전기이월_F비용T선급금.xlsx',{cellStyles:true})}
function downloadReversalMd(){if(!window.REVERSAL_ROWS?.length){alert('먼저 환원전표를 생성해 주세요.');return}const rows=window.REVERSAL_ROWS;const md=['# 전기이월_F비용T선급금','','| 상태 | 사업ID | 계정과목명 | 계정과목 | 차대구분 | 차변금액 | 대변금액 | 결의번호 |','|---|---|---|---|---|---:|---:|---|',...rows.map(r=>`| ${r.상태} | ${r.사업ID} | ${r.계정과목명} | ${r.계정과목코드} | ${r.차대구분} | ${r.차변금액} | ${r.대변금액} | ${r.rsolNo} |`)].join('\n');const blob=new Blob([md],{type:'text/markdown;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='전기이월_F비용T선급금.md';a.click();URL.revokeObjectURL(a.href)}
function setAccountWorkspaceVisible(show){const hero=document.getElementById('dashboardHero');if(hero)hero.hidden=show;['accountIntro','upload','uploadGrid','plannedNotice','reviewPanel','assetCenter','journalPanel','reversalPanel'].forEach(id=>{const el=document.getElementById(id);if(el)el.hidden=!show})}
function renderAccountState(account){const built=account==='선급금';const intro=document.getElementById('accountIntro');const grid=document.getElementById('uploadGrid');const notice=document.getElementById('plannedNotice');const title=document.getElementById('uploadTitle');const hint=document.getElementById('uploadHint');if(intro)intro.hidden=!built;if(grid)grid.hidden=!built;if(notice)notice.hidden=built;if(title)title.textContent=built?'자료 업로드':`${account} 검토`;if(hint)hint.textContent=built?'아래에서 실제 파일을 선택하면 아알크 검토가 시작됩니다':`${account} 계정과목 검토 모듈은 구축 예정입니다.`;if(!built){const name=document.getElementById('plannedAccountName');if(name)name.textContent=`${account} 계정과목은`}}
function openDashboardHome(fromHistory=false){setAccountWorkspaceVisible(false);applyView('dashboard');if(!fromHistory&&history.state?.arcView!=='dashboard'){history.pushState({arcView:'dashboard',arcStage:'dashboard'},'',`${location.pathname}${location.search}#dashboard`)}}
function selectAccount(account,fromHistory=false){setAccountWorkspaceVisible(true);renderAccountState(account);applyView('dashboard');if(!fromHistory&&history.state?.account!==account){history.pushState({arcView:'dashboard',arcStage:'dashboard',account},'',`${location.pathname}${location.search}#account-${encodeURIComponent(account)}`)}document.getElementById('upload')?.scrollIntoView({behavior:'smooth',block:'start'})}
function goDashboardSection(id){selectAccount('선급금');if(id){history.replaceState({arcView:'dashboard',arcStage:'dashboard',section:id,account:'선급금'},'',`#${id}`);document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'})}}
const initialView=location.hash==='#standards'?'standards':location.hash==='#ai-deep'?'aiDeep':'dashboard';history.replaceState({arcView:initialView,arcStage:'dashboard'},'',`${location.pathname}${location.search}${initialView==='standards'?'#standards':initialView==='aiDeep'?'#ai-deep':''}`);if(initialView==='standards'||initialView==='aiDeep')applyView(initialView);else openDashboardHome(true);
